// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqlgoxcdumilhdirsubl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbGdveGNkdW1pbGhkaXJzdWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODY2MjAsImV4cCI6MjA3MjY2MjYyMH0.GfMZtWzwKVoODXvumGu8Iu0_Hg7ynwCBAktZgkmeB98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});